<a href="https://colab.research.google.com/github/Anugrahsr/Assignment/blob/master/datacamp4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LOGIC AND CONTROL FLOW




[github source](https://github.com/AmoDinho/datacamp-python-data-science-track/blob/master/Intermediate%20Python%20for%20Data%20Science/Slides/intermediate_python_ch3_slides.pdf)



**#Equality**

In [1]:
# Comparison of booleans
print(True == False)

False


In [2]:
# Comparison of integers
print(-5 * 15 != 75)

True


In [6]:
# Comparison of strings
print("pyscript" == "PyScript")

False


In [10]:
# Compare a boolean with a numeric
print(True == 1)
print(False == 1) #False is true when compared to 0


True
False


**#Greater and less than**

In [11]:
# Comparison of integers
x = -3 * 6
print(x >= -10)

False


In [12]:
# Comparison of strings
y = "test"
print("test" <= y)


True


In [13]:

# Comparison of booleans
print(True > False)

True



**#Compare arrays**

In [37]:
#compare two array
import numpy as np
my_array1 = np.array([1, 2, 3, 4, 5, 6])
my_array2 = np.array([5, 7, 8, 3, 6, 9])

print(my_array1 <= 3)

[ True  True  True False False False]


In [15]:
#compare two array
print(my_array1 < my_array2)

[ True  True  True False  True  True]


In [16]:
print(my_array1 < 3 and my_array2 > 2)
#oops error!

ValueError: ignored

**#Boolean operators with Numpy**



1.   np.logical_and
2.   np.logical_or
3.   np.logical_not



In [17]:
logic1 = np.logical_and(my_array1 < 3, my_array2 > 2)

array([ True,  True, False, False, False, False])

In [20]:
my_array1[np.logical_and(my_array1 < 3, my_array2 > 2)]

array([1, 2])

In [0]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])


In [22]:
# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5, my_house < 10))

[False  True False  True]


In [23]:
# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[False False False  True]


# **Condition Statements**

**#If**

In [0]:
# Define variables
room = "kit"
area = 14.0

In [30]:
if room == "kit":
  print("hello world")

hello world


In [31]:
# if-else construct for area :
if area > 15 :
    print("big place!")
else :
    print("pretty small.")


pretty small.


In [32]:
# if-elif-else construct for area
if area > 15 :
    print("big place!")
elif area > 10 :
    print("medium size, nice!")
else :
    print("pretty small.")

medium size, nice!


In [0]:
#Cars per capita (2)
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Import numpy, you'll need this
import numpy as np

# Create medium: observations with cars_per_cap between 100 and 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Print medium
print(medium)

**while Loop**

In [33]:
x = 50.0

while x > 1:
  x = x / 4
  print(x)


12.5
3.125
0.78125


In [35]:
offset = 10
while offset != 0 :
    print("correcting...")
    offset = offset - 1
    print(offset)

correcting...
9
correcting...
8
correcting...
7
correcting...
6
correcting...
5
correcting...
4
correcting...
3
correcting...
2
correcting...
1
correcting...
0


In [36]:
#Loop over a list
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for area in areas :
    print(area)

11.25
18.0
20.0
10.75
9.5


In [38]:
for i in my_array1:
  print(i)

1
2
3
4
5
6


In [40]:
for i in my_array1:
  print(f'index of my_array[{i-1}] is {i}')

index of my_array[0] is 1
index of my_array[1] is 2
index of my_array[2] is 3
index of my_array[3] is 4
index of my_array[4] is 5
index of my_array[5] is 6


In [0]:

#Indexes and values (1)
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

**Enumerate**

In [42]:
# Code the for loop
for index, area in enumerate(areas) :
    print("room " + str(index) + ": " + str(area))


room 0: 11.25
room 1: 18.0
room 2: 20.0
room 3: 10.75
room 4: 9.5


In [44]:
for index, i in enumerate(my_array1):
  print(f'{str(index)} is the index of my_array where it\'s value is {i}')

0 is the index of my_array where it's value is 1
1 is the index of my_array where it's value is 2
2 is the index of my_array where it's value is 3
3 is the index of my_array where it's value is 4
4 is the index of my_array where it's value is 5
5 is the index of my_array where it's value is 6


In [49]:
for i in "family":
  print(f'{i.capitalize()}')

F
A
M
I
L
Y


In [0]:
#Loop over list of lists
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]

In [53]:
for i in house:
  print(f'the {i[0]} is {i[1]} sq.meters')

the hallway is 11.25 sq.meters
the kitchen is 18.0 sq.meters
the living room is 20.0 sq.meters
the bedroom is 10.75 sq.meters
the bathroom is 9.5 sq.meters


In [0]:
#Loop over dictionary
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn', 
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'australia':'vienna' }

In [57]:
for key, value in europe.items():
  print(f'the capital of {key} is {value}')

the capital of spain is madrid
the capital of france is paris
the capital of germany is bonn
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of australia is vienna


**Array**

In [0]:
val = my_array1 / my_array2

In [59]:
val

array([0.2       , 0.28571429, 0.375     , 1.33333333, 0.83333333,
       0.66666667])

In [60]:
for i in val:
  print(i)

0.2
0.2857142857142857
0.375
1.3333333333333333
0.8333333333333334
0.6666666666666666


In [0]:
measure = np.array([my_array1, my_array2])

In [63]:
measure

array([[1, 2, 3, 4, 5, 6],
       [5, 7, 8, 3, 6, 9]])

In [64]:
for i in measure:
  print(i)

[1 2 3 4 5 6]
[5 7 8 3 6 9]


In [65]:
for i in np.nditer(measure):
  print(i)

1
2
3
4
5
6
5
7
8
3
6
9


![alt text](https://i.ibb.co/MpBSqh0/Firefox-Screenshot-2020-01-23-T12-28-51-932-Z.png)

In [0]:
import pandas as pd

df = pd.DataFrame(house)

In [76]:
df

0      1
0      hallway  11.25
1      kitchen  18.00
2  living room  20.00
3      bedroom  10.75
4     bathroom   9.50

In [83]:
for lab, row in df.iterrows():
  print(row[int(0)])

hallway
kitchen
living room
bedroom
bathroom


In [102]:
for lab, row in df.iterrows():
  print(row[int(0)])
  df.loc[lab,'new'] = len(row[int(0)])

hallway
kitchen
living room
bedroom
bathroom


In [103]:
df

0      1   new
0      hallway  11.25   7.0
1      kitchen  18.00   7.0
2  living room  20.00  11.0
3      bedroom  10.75   7.0
4     bathroom   9.50   8.0

In [0]:
for lab, row in df.iterrows():
  df["upper_name"] = df[int(0)].apply(str.upper)

In [109]:
df

0      1   new   upper_name
0      hallway  11.25   7.0      HALLWAY
1      kitchen  18.00   7.0      KITCHEN
2  living room  20.00  11.0  LIVING ROOM
3      bedroom  10.75   7.0      BEDROOM
4     bathroom   9.50   8.0     BATHROOM