<a href="https://colab.research.google.com/github/Anugrahsr/Assignment/blob/master/datacamp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Datacamp Introduction to python




In [0]:
import numpy as np

In [0]:
test = np.array([1,2,3,4])

variable cannot start with number
--
___

In [0]:
import matplotlib as plt 
import pandas as pd

|float | int | str | bool|



In [0]:
print (f'hellow {test}')

hellow [1 2 3 4]


[start] : [end]
`included` : `excluded`

In [0]:
test[1:3]

array([2, 3])

In [0]:
test[:1]

array([1])

In [0]:
test[:-1]

array([1, 2, 3])

array[x][y]

In [0]:
array_copy = test[:]

In [0]:
max(test)

4

In [0]:
round(1.78)

2

In [0]:
round(1.87,2)

1.87

In [0]:
round(1.87,1)

1.9

In [0]:
len('hello')

5

**Help**
___
`help`
`?`





In [0]:
?complex

In [0]:
?sorted

In [0]:
m = ["hi", 3.4, 76, 6, "kmm"]

In [0]:
m.index("hi")

0

In [0]:
m.count(6)

1

In [0]:
sis = "lizaa"


**Capitalize first letter**

In [0]:
print(sis.capitalize())

Lizaa


**Replace**

In [0]:
sis.replace("aa", "ee")

'lizee'

In [0]:
sis.upper()

'LIZAA'

In [0]:
sis.lower()

'lizaa'

**Append Reverse Remove**



In [0]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

In [0]:
# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


import maths package

In [0]:
import math
#2 is the radius
area = math.pi * 2**2

In [0]:
print(area)

12.566370614359172


**Example for radians package in math**

In [0]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


## Numpy

In [0]:
import numpy as np

In [0]:
a = np.array([1, 3, 5, 7, 8, 2])

In [0]:
b = np.array([3, 5, 7, 7, 9 ,6])

In [0]:
bmi = a / b**2

In [0]:
print(bmi)

[0.11111111 0.12       0.10204082 0.14285714 0.09876543 0.05555556]


In [0]:
sum(a*b)

186

In [0]:

# height and weight are available as regular lists
height_in = [10 , 3, 65, 7, 7]
weight_lb = [4, 57, 7, 8, 8]
# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_lb = np.array(weight_lb)
np_weight_kg = np_weight_lb * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

[2.81227602e+01 4.45277037e+03 1.16484806e+00 1.14786777e+02
 1.14786777e+02]


____

In [0]:
x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]


9

bool subseting

In [0]:
high = y > 5
y[high]


array([9, 6])

In [0]:
# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False  True False False]
[1.16484806]


In [0]:
x = ["a", "b", "c"]
x[1]

np_x = np.array(x)
np_x[1]
print(np_x[1])


b


In [0]:
x[1]

'b'

# 2d Numpy array

In [0]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball

np_baseball = np.array(baseball)
# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [0]:
print(np_baseball[1,:])

[215.  102.7]


In [0]:
# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[2,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[3,0])

[210.   98.5]
188.0


In [0]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

np_mat + np_mat
#Added array to itself

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [0]:
np_mat * 2
#Array multipied by 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [0]:
np_mat + np.array([10, 10])
#all elemts of array are added with [10,10]

array([[11, 12],
       [13, 14],
       [15, 16]])

----

In [0]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

NameError: ignored

**Basic Stat**

In [0]:
import numpy as np
x = [1, 4, 8, 10, 12]
np.mean(x)
np.median(x)

8.0

In [0]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

198.25
199.0


**mean median sd correlation**

In [0]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


In [0]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)


# Heights of the goalkeepers: gk_heights

gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

NameError: ignored